name: Test Graphviz Install

on: workflow_dispatch # you can trigger it manually from the GitHub UI

jobs:
  test-graphviz:
    runs-on: ubuntu-24.04 # or ubuntu-latest if you want

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run installation script
        run: ./install.sh
