name: Test Graphviz Install

on: workflow_dispatch # you can trigger it manually from the GitHub UI

jobs:
  deb_install:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run installation script
        run: ./install.sh

  deb_cached:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Graphviz .deb files
        uses: actions/cache@v4
        with:
          path: debs
          key: graphviz-debs-${{ runner.os }}-ubuntu-24.04-v1

      - name: Show contents of debs/ folder (debug)
        run: |
          echo "Contents of debs/:"
          ls -lh debs

      - name: Run installation script
        run: ./install.sh

  via_action:
    runs-on: ubuntu-24.04

    steps:
      - name: Install Graphviz via action
        uses: ts-graphviz/setup-graphviz@v2
      - name: Verify Graphviz installation
        run: |
          dot -vV
          if ! command -v dot &> /dev/null; then
            echo "Graphviz installation failed"
            exit 1
          fi
          echo "Graphviz installed successfully"

  via_apt_install:
    runs-on: ubuntu-24.04

    steps:
      - name: Install Graphviz via apt
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
      - name: Verify Graphviz installation
        run: |
          dot -vV
          if ! command -v dot &> /dev/null; then
            echo "Graphviz installation failed"
            exit 1
          fi
          echo "Graphviz installed successfully"

  via_apt_install_without_update:
    runs-on: ubuntu-24.04

    steps:
      - name: Install Graphviz via apt without update
        run: |
          sudo apt-get install -y graphviz
      - name: Verify Graphviz installation
        run: |
          dot -vV
          if ! command -v dot &> /dev/null; then
            echo "Graphviz installation failed"
            exit 1
          fi
          echo "Graphviz installed successfully"

  via_apt_install_without_update_and_recommends:
    runs-on: ubuntu-24.04

    steps:
      - name: Install Graphviz via apt without update and recommends
        run: |
          sudo apt-get install --no-install-recommends -y graphviz
      - name: Verify Graphviz installation
        run: |
          dot -vV
          if ! command -v dot &> /dev/null; then
            echo "Graphviz installation failed"
            exit 1
          fi
          echo "Graphviz installed successfully"
